### ISSUE TITLE
Auto Updates?

### ISSUE THREAD

**Issue by maxfield-allison** [marcermarc/DockerSteam#1]
Will this image auto update the game server? Is there a docker compose example?

**Comment by marcermarc** [comment]
Hello,
the image is updated weekly by my Jenkins. An update within the image is not planned by me. So you have to re-pull the image to update it. 
Unfortunately the project zomboid image is broken. Since I don't need a server for this game at the moment, I stopped the support for this image. The garrysmod image and the steam-base image work fine.
Docker compose files are currently not provided.
Many greetings marcermarc
